name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set safe directory
        run: git config --global --add safe.directory /home/runner/work/calc2-tp01/calc2-tp01

      - name: Create build/docs directory
        run: mkdir -p build/docs

      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          doxyfile-path: docs/Doxyfile
          html-output-folder: build/docs/html
          branch: gh-pages